version: "3.6"

volumes:
  got-your-back-persistant:

services:

  got-your-back:

    image: geroldpenz/got-your-back

    build:
      context: ../
      dockerfile: docker/Dockerfile

    restart: "no"

    environment:
      PERSISTANT_DIR: "/app/persistant"

    volumes:
      - got-your-back-persistant:/app/persistant

#    command: redis-server /etc/redis/redis.conf --requirepass chKcgha1cxXX


